version: '2'

services:
  remote-write:
    image: anodot/prometheus-remote-write
    container_name: anodot-prometheus-remote-write
    restart: unless-stopped
    environment:
      ANODOT_LOG_LEVEL: "3"
      ANODOT_HTTP_DEBUG_ENABLED: "false"
      # see https://github.com/anodot/anodot-remote-write/wiki/2.-Installation for more details
      ANODOT_URL: "https://api.anodot.com"
      ANODOT_API_TOKEN: "CHANGE_ME"
      ANODOT_ACCESS_KEY: "CHANGE_ME"
    ports:
      - "1234:1234"
    # used to join default docker bridge network
    #network_mode: bridge

# uncomment to join existing user-defined network, so containers can communicate with each other by container name
# see details https://docs.docker.com/compose/networking/
#networks:
#  default:
#    external:
#      name: <change_with_existing_network>
