{{ if .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    labels:
        app: {{ template "template_name" . }}
        requiredBy: "anodot"
{{- if .Values.prometheus.serviceMonitor.labels}}
    {{ toYaml .Values.prometheus.serviceMonitor.labels | indent 4 }}
{{- end }}
    name: {{ template "template_name" . }}
spec:
    jobLabel: {{ .Values.prometheus.serviceMonitor.jobLabel }}
    namespaceSelector:
        any: true
    selector:
        matchLabels:
            app: {{ template "template_name" . }}
            release: {{ .Release.Name }}
    endpoints:
    - port: http
            {{- if .Values.prometheus.serviceMonitor.interval }}
      interval: {{ .Values.prometheus.serviceMonitor.interval }}
            {{- end }}
            {{- if .Values.prometheus.serviceMonitor.metricRelabelings }}
      metricRelabelings:
{{ tpl (toYaml .Values.prometheus.serviceMonitor.metricRelabelings | indent 8) . }}
            {{- end }}
{{- if .Values.prometheus.serviceMonitor.relabelings }}
      relabelings:
{{ toYaml .Values.prometheus.serviceMonitor.relabelings | indent 8 }}
            {{- end }}
{{- end }}