apiVersion: v1
kind: Service
metadata:
  name: {{ template "template_name" . }}
spec:
  selector:
    app: {{ template "template_name" . }}
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: 1234
      targetPort: 1234