image:
  repository: anodot/prometheus-remote-write
  tag: "1.3.0"
  pullPolicy: IfNotPresent

configuration:
  replicas: 1
  args:
    - "--url=http://anodotd:8080/api/v1/"
    - "--token=XXXXXXXXX"

resources:
  requests:
    memory: '4Gi'
    cpu: '150m'
  limits:
    memory: '5Gi'
    cpu: '300m'

livenessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 2
  periodSeconds: 30
readinessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 2
  periodSeconds: 30

service:
  type: ClusterIP
