version: '3.1'

services:

  anodot-metrics-stub:
    container_name: anodot-metrics-stub
    image: anodot/anodot-metrics-stub:v0.1.0
    ports:
      - 8080:8080/tcp
    environment:
      DEBUG: "true"
      DUMP_REQUEST_FILE: "/tmp/metrics.log"
      ANODOT_API_TOKEN: "123456"

  prometheus:
    image: prom/prometheus:latest
    depends_on:
      - remote-write
    ports:
      - 9090:9090/tcp
    volumes:
      - ./sample-docker-prometheus.yml:/etc/prometheus/prometheus.yml:ro

  remote-write:
    image: anodot/prometheus-remote-write:1.5.0
    container_name: anodot-prometheus-remote-write
    depends_on:
      - anodot-metrics-stub
    restart: unless-stopped
    ports:
      - "1234:1234"
    command: ["-url=http://anodot-metrics-stub","--port=8080","-token=123456","-workers=20"]
    environment:
      ANODOT_METRICS_PER_REQUEST_SIZE: 4
      ANODOT_LOG_LEVEL: "trace"
