version: '3.1'

services:

  anodot-metrics-stub:
    container_name: anodot-metrics-stub
    image: anodot/anodot-metrics-stub:v0.1.0
    ports:
      - 8080:8080/tcp
    environment:
      DEBUG: "true"
      DUMP_REQUEST_FILE: "/tmp/metrics.log"
      ANODOT_API_TOKEN: "123456"

  prometheus:
    image: prom/prometheus:latest
    depends_on:
      - remote-write
    ports:
      - 9090:9090/tcp
    volumes:
      - ./sample-docker-prometheus.yml:/etc/prometheus/prometheus.yml:ro

  remote-write:
    image: anodot/prometheus-remote-write:2.3.3-beta
    container_name: anodot-prometheus-remote-write
    depends_on:
      - anodot-metrics-stub
    restart: unless-stopped
    volumes:
      - ./metric-relabel.yml:/mnt/relabel.yml:ro
    ports:
      - "1234:1234"
    command: ["-url=http://anodot-metrics-stub:8080","-token=should_be_taken_from_env","-workers=20"]
    environment:
      ANODOT_METRICS_PER_REQUEST_SIZE: 4
      ANODOT_LOG_LEVEL: "5"
      ANODOT_API_TOKEN: "123456"
      ANODOT_RELABEL_CONFIG_PATH: "/mnt/relabel.yml"
      ANODOT_HTTP_DEBUG_ENABLED: "true"
      ANODOT_PUSH_METRICS_ENABLED: "true"
#      ANODOT_REMOTE_WRITE_USER: "_q_pW3Q9KBNguDkAP28WC2BiG4jYz1"
#      ANODOT_REMOTE_WRITE_PASSWORD: "RWx91_Ub_jzV@l21mRlB0RowF1r0jP"

  vm-agent:
    image: victoriametrics/vmagent:latest
    container_name: vm-agent
    restart: unless-stopped
    ports:
      - "8429:8429"
    command: ["-remoteWrite.url=http://remote-write:1234/receive","-remoteWrite.url=http://vm:8428/api/v1/write"]

  vm:
    image: victoriametrics/victoria-metrics
    container_name: vm
    restart: unless-stopped
    ports:
      - "8428:8428"
      #command: ["-remoteWrite.url=http://remote-write:1234/receive","-remoteWrite.url=http://vm:8428/api/v1/write"]