global:
  scrape_interval:     3s
  evaluation_interval: 1s

remote_write:
  - url: "http://remote-write:1234/receive"
    write_relabel_configs:
      - source_labels: [anodot_include]
        regex: 'true'
        action: keep
      - source_labels: [job]
        regex:         (.*)
        target_label:  anodot_tag_job
        replacement:   ${1}
      - regex: '(job)'
        action: labeldrop
    queue_config:
      batch_send_deadline: 1s

scrape_configs:
  - job_name: 'test-app'
    metrics_path: '/stub/metrics'

    static_configs:
      - targets: ['anodot-metrics-stub:8080']

    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(exported_http_requests_total|exported_version)'
        replacement: 'true'
        target_label: 'anodot_include'